### PR TITLE
[obsolete] Fix compile bug for Mac OS X 10.13.6

### LINKED ISSUE #7092: Master does not compile on Mac OS X 10.13.6 with GCC 10.4.2
### Describe the issue

Master does not compile on Mac OS X 10.13.6 with GCC 10.4.2.

Compilation stops in shm_unix.h with the following error message:

```
shm_unix.h: In member function 'Stockfish::shm::UniqueFd Stockfish::shm::SharedMemory<T>::try_receive_memfd(const std::string&)':
shm_unix.h:380:36: error: size of array 'buf' is not an integral constant-expression
  380 |                 char           buf[CMSG_SPACE(sizeof(int))];
````

### Expected behavior

Successful compilation

### Steps to reproduce

make clean
make -j build COMP=gcc

### Anything else?

The problem is that on such systems CSMG_SPACE() is not a compile time constant, so it cannot be used to allocate the size of the message buffer we use in shm_unix.h

One tentative fix using a dynamic array instead of a stack array for the message buffer has been push in pull request https://github.com/official-stockfish/Stockfish/pull/7091

### Operating system

Mac OS X (Darwin)

### Stockfish version

229f6339e537a097a79831cd06dbfdb3e623d4ac

### PR DESCRIPTION
**Pull request by snicolet**
Master branch does not compile on some Macintosh systems since commit d077f9a8154df309b1b715e51d663e4cd6cf8e73 (for instance compilation fails on Mac OS X 10.13.6 using GNUC 10.4.2).

The problem is that on such systems CSMG_SPACE() is not a compile time constant, so it cannot be used to allocate the size of the message buffer we use in shm_unix.h . The fix is to use a dynamic array instead of a stack array for the buffer.

fixes  https://github.com/official-stockfish/Stockfish/issues/7092
closes https://github.com/official-stockfish/Stockfish/pull/7091

No functional change

### CODE REVIEW

File: src/shm_unix.h [hunk 1]
```diff
@@ -375,21 +375,17 @@ class SharedMemory {
             iov[0].iov_len  = 1;
             msg.msg_iov     = iov;
             msg.msg_iovlen  = 1;
+            char *control_msg_buffer = new char[CMSG_SPACE(sizeof(cmsghdr)) + 1024];
```
Comment (Disservin) [inline src/shm_unix.h]: unique pointer?

Comment (snicolet) [reply src/shm_unix.h]: What do you mean exactly? The master version was allocating the union on the stack, and I don't know exactly if alignment was necessary for the buffer used int the calls in socket.h : so I used a little epsilon of room (1Kb) for the buffer size.

Comment (Disservin) [reply src/shm_unix.h]: put the allocation inside the constructor of a unique ptr and then we can delete the manual delete calls
