### PR TITLE
Improve Makefile for Windows builds

### PR DESCRIPTION
**Pull request by ppigazzini**
A Windows Native Build (WNB) can be done:
 - on Windows, using a recent mingw-w64 g++/clang compiler
   distributed by msys2, cygwin and others
 - on Linux, using mingw-w64 g++ to cross compile

Improvements:
 - check for a WNB in a proper way and set a variable to simplify the code
 - set the proper EXE for a WNB
 - use the proper name for the mingw-w64 clang compiler
 - use the static linking for a WNB
 - use wine to make a PGO cross compile on Linux (also with Intel SDE)
 - enable the LTO build for mingw-w64 g++ compiler
 - set `lto=auto` to use the make's job server, if available, or otherwise
   to fall back to autodetection of the number of CPU threads
 - clean up all the temporary LTO files saved in the local directory

Tested on:
 - msys2 MINGW64 (g++), UCRT64 (g++), MINGW32 (g++), CLANG64 (clang)
   environments
 - cygwin mingw-w64 g++
 - Ubuntu 18.04 mingw-w64 PGO cross compile (also with Intel SDE)

closes #3891

### CODE REVIEW

**Comment by pschneider1968** [comment]
That's a really nice simplication! I checked out you repo with changes upto 4b6944d in your msys2_makefile branch, and tested 64 bit builds with Clang and GCC, using MSYS2/Windows 10 and Linux (up to date Fedora 35), and can confirm that everything builds and works fine. "make strip" now works also on Windows (previously, it did not). MINGW64 builds now use -flto=auto, which (on my machine) makes it speedwise upto par with the CLANG64 build:

```
Peter@bolide MINGW64 ~/repos/ppigazzini/Stockfish/src
$ bench-parallel.sh ~/repos/pschneider1968/Stockfish/src/stockfish.exe ~/repos/ppigazzini/Stockfish/src/stockfish.exe 13 10
run   1 / 10
run   2 / 10
run   3 / 10
run   4 / 10
run   5 / 10
run   6 / 10
run   7 / 10
run   8 / 10
run   9 / 10
run  10 / 10

run     sf_base sf_test diff
  1  1294942  1293816  -1126
  2  1344868  1347302  +2434
  3  1326883  1328462  +1579
  4  1342845  1346896  +4051
  5  1305162  1320213  +15051
  6  1345273  1356306  +11033
  7  1302497  1308222  +5725
  8  1319433  1318264  -1169
  9  1329253  1330441  +1188
 10  1329649  1335615  +5966

sf_base =    1324080 +/- 11303
sf_test =    1328553 +/- 11881
diff =       4473 +/- 3236
speedup = 0.003378


Peter@bolide MINGW64 ~/repos/ppigazzini/Stockfish/src
$
```

First one, from my repo checkout is CLANG64 build, second one is MINGW64 build with your Makefile changes. My desktop Windows machine where I tested with MSYS2 is an older Sandy Bridge Core i7 2600K, 4 cores, 8 threads, 16GB RAM, slightly overclocked to 3.8 GHz (original 3.4 GHz).
My Linux machine has worse single core performance but it has 2x12 = 24 cores, 48 threads. It is an older Ivy Bridge 2x Xeon 2697v2, with 256 GB RAM @2.7 GHz. I plan to (part time) run fishtest on this machine...

**Comment by ppigazzini** [comment]
> You have a slight typo here in line 408: `ifeq ($(target_windows),**yew**)` instead of `yes`

Thank you, multi tasking, I pushed an incomplete commit :(

**Comment by pschneider1968** [comment]
> > You have a slight typo here in line 408: `ifeq ($(target_windows),**yew**)` instead of `yes`
> 
> Thank you, multi tasking, I pushed an incomplete commit :(

Multitasking only works in CPUs, but not in our human brains 😉😁

**Comment by pschneider1968** [comment]
I retested your changes upto 7a82c8a, building with CLANG64 and MINGW64 under Windows, and Clang and GCC under Linux, and everything is looking good and working fine.

Only small exception is that under Linux using GCC, parallel linking is still broken (=> slow) as in #3656 when invoking ``make -j`` without numerical argument, but that induces only the warning ``lto-wrapper: Warnung: jobserver is not available: »--jobserver-auth=« is not present in »MAKEFLAGS«`` but does not break the build.

**Comment by vondele** [comment]
I'm testing this PR on linux, but I'm getting error messages for the PGO-ed cross to windows:

```
make clean && make -j profile-build ARCH=x86-64-bmi2         COMP=mingw
[...]
/usr/bin/x86_64-w64-mingw32-ld: stockfish.exe.ltrans0.ltrans.o:<artificial>:(.text+0x159): undefined reference to `__gcov_indirect_call_profiler_v3'
[...]
```

maybe there are just missing packages?

**Comment by ppigazzini** [comment]
I'm able to cross build only on Ubuntu 18.04 (check the wiki script), on Ubuntu 20.04 returned that annoying bug on gcov.
https://github.com/glinscott/fishtest/wiki/Building-Stockfish-on-Windows#cross-compilation-with-ubuntu-1804

**Comment by vondele** [comment]
OK, yeah, looks like a 20.04 bug indeed. I wonder if this will affect abrok. We do have this info:

They are compiled with gcc 11.2/mingw 10 on Ubuntu 21.10.

**Comment by ppigazzini** [comment]
I'm commuting now, when at home I will try on a newer Ubuntu. Usually that bug skips one LTS version and hits the next.

**Comment by ppigazzini** [comment]
The wiki script runs fine for Ubuntu 21.10, PGO working.
```
Step 2/4. Running benchmark for pgo-build ...
/usr/bin/wine ./stockfish.exe bench 2>&1 | tail -n 4
===========================
Total time (ms) : 4852
Nodes searched  : 4464962
Nodes/second    : 920231
```

```
root@u2110:~/Stockfish/src# wine ./stockfish.exe compiler
Stockfish 190122 by the Stockfish developers (see AUTHORS file)

Compiled by g++ (GNUC) 10.0.0 on MinGW64
Compilation settings include:  64bit SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: 10-posix 20210610
```

**Comment by ppigazzini** [comment]
SDE works too:
```
Step 2/4. Running benchmark for pgo-build ...
/root/sde-external-9.0.0-2021-11-07-lin/sde64 -- /usr/bin/wine ./stockfish.exe bench 2>&1 | tail -n 4
===========================
Total time (ms) : 88995
Nodes searched  : 4464962
Nodes/second    : 50170
```

```
root@u2110:~/Stockfish/src# /root/sde-external-9.0.0-2021-11-07-lin/sde64 -- wine stockfish.exe compiler
Stockfish 190122 by the Stockfish developers (see AUTHORS file)

Compiled by g++ (GNUC) 10.0.0 on MinGW64
Compilation settings include:  64bit AVX512 BMI2 AVX2 SSE41 SSSE3 SSE2 POPCNT
__VERSION__ macro expands to: 10-posix 20210610
```

**Comment by vondele** [comment]
OK, that's neat.

**Comment by vondele** [comment]
@ppigazzini I think some fishtest workers are experiencing issues right now. https://tests.stockfishchess.org/actions?count=1&before=1642631376.745

**Comment by ppigazzini** [comment]
The worker with many failures is running on Darwin NEON
https://tests.stockfishchess.org/actions?count=1&before=1642626928.619
```
Ulysses-4cores-d18217c9 | os: Darwin 21.2.0; ram: 8192MiB; gcc: 12.0.5; python: 3.8.2; worker: 147; arch: 64bit POPCNT NEON
```

The worker reported by you has a strange error, the option '-j 3' has a positive integer argument.
```
make COMP=mingw ARCH=x86-64-bmi2 -j 3 profile-build failed. Error: ["make: the '-j' option requires a positive integer argument\n"
```

**Comment by ppigazzini** [comment]
I started a new test on DEV, the msys2 worker run fine.

Idx | Worker | Info | Last Updated | Played | Pentanomial [0‑2] 
-- | -- | -- | -- | -- | -- 
0 | user00-3cores-3877a472 | os: Windows 10; ram: 16224MiB; gcc: 11.2.0; python: 3.9.7; worker: 148; arch: 64bit SSE41 SSSE3 SSE2 POPCNT | 2022-01-19 23:07:55 | 016 / 176 | [0, 1, 5, 2, 0]

Perhaps the worker `robal-3cores-79878e22` needs to update msys2

https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Windows#msys2

5. from time to time (suggested monthly) update Chocolatey and the MSYS2 packages:
    - stop the worker
    - right click on 04_update_msys2_choco_admin.cmd, select Run as administrator, approve if asked for. This requires a couple of minutes in a system updated regularly
    - start the worker

**Comment by ppigazzini** [comment]
This https://github.com/glinscott/fishtest/pull/1253 should fix the problem for a worker on Darwin NEON using gcc.

**Comment by pschneider1968** [comment]
I successfully tested the profile-build cross compile to Windows using current Fedora 35, with these versions:

x86_64-w64-mingw32-c++ (GCC) 11.2.1 20210728 (Fedora MinGW 11.2.1-3.fc35)
GNU ld version 2.37-3.fc35
wine-7.0-rc6 (Staging)

On Fedora, manual installation of the package mingw64-winpthreads-static is required, however, otherwise the linker complains that it cannot find -lpthread.

The built executable works fine (albeit slow) in wine, and works fine on native Windows.

**Comment by vondele** [comment]
I suspect that this `"make: the '-j' option requires a positive integer argument\n"` error results from the -flto=auto option... maybe depends on the version of make/gcc.

**Comment by ppigazzini** [comment]
See https://github.com/glinscott/fishtest/issues/1255

**Comment by mstembera** [comment]
@ppigazzini  @vondele 
I apologize for not catching this sooner but this breaks clang builds on windows.   When I execute
```make build ARCH=x86-64-bmi2 COMP=clang -j```
I now get
```
make[1]: x86_64-w64-mingw32-clang++: No such file or directory
make[1]: *** [<builtin>: benchmark.o] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: x86_64-w64-mingw32-clang++: No such file or directory
make[1]: *** [<builtin>: bitbase.o] Error 127
make[1]: Leaving directory '/c/Projects/Stockfish/src'
make: *** [Makefile:781: build] Error 2
```
before this patch the same command builds successfully w/o any warnings or errors.
My clang version is
```
clang version 13.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/mingw64/bin
```

**Comment by pschneider1968** [comment]
It seems you tried the build using the MINGW64 launcher which sets up the environment for MINGW64 GCC. In that environment, `x86_64-w64-mingw32-clang++` is not in the PATH.

How did you call `clang `in that enviroment anyway to get the version? Because, also neither `clang ` nor `clang++` is in the PATH in that env. And that it says it's intalled in `C:/msys64/mingw64/bin` is outright strange; it looks like something in your MSYS2 setup is really messed up.

Please try to use the CLANG64 launcher. When I saw your comment, I just tested it again, and it all works fine for me.

**Comment by ppigazzini** [comment]
I set that name because it's the only one used in cygwin (same for cygwin's gcc).

msys2 uses several aliases:
```
# /c/tools/msys64/clang64/bin
# ls *{c++,g++,clang}*.exe
c++.exe      clang++.exe      clang-extdef-mapping.exe   clang-offload-wrapper.exe  clang-repl.exe       g++.exe                         x86_64-w64-mingw32-clang++.exe
c++filt.exe  clang-check.exe  clang-format.exe           clang-refactor.exe         clang-scan-deps.exe  x86_64-w64-mingw32-c++.exe      x86_64-w64-mingw32-clang.exe
clang++.exe  clang-cpp.exe    clang-offload-bundler.exe  clang-rename.exe           clang.exe            x86_64-w64-mingw32-clang++.exe  x86_64-w64-mingw32-g++.exe
```

Install clang for native Windows (ucrt) with this command:
```
pacman -S --noconfirm --needed mingw-w64-clang-x86_64-gcc
```

To be used with a clang64 environment starting the right launcher, eg:
```
C:\tools\msys64\msys2_shell.cmd -clang64
C:\tools\msys64\clang64.exe
```

**Comment by ppigazzini** [comment]
Wiki page updated with Clang/LLVM info/instructions/script.
https://github.com/glinscott/fishtest/wiki/Building-Stockfish-on-Windows

**Comment by mstembera** [comment]
@pschneider1968 @ppigazzini  Thank you both very much for responding!

I originally installed everything as described in the instructions here https://github.com/glinscott/fishtest/wiki/Building-Stockfish-on-Windows but they may have been updated since I did so. I run everything from the standard windows command prompt C:\WINDOWS\system32\cmd.exe and have C:\msys64\mingw64\bin included in my PATH environment variable.

After reading your comments I was able to fix the issue by installing the mingw-w64-clang-x86_64-clang package and adding C:\msys64\clang64\bin to my PATH.  No launchers, or any custom command prompts, or shells necessary(which I frankly prefer because everything else also runs from the default windows command prompt as it should).

**Comment by ppigazzini** [comment]
If you want to use the windows command prompt with several environments (eg clang64, ucrt64, mingw64), create some shortcut to the `msys2_shell.cmd` launcher:
- clang64
target: 
"C:\tools\msys64\msys2_shell.cmd -clang64 -defterm"
start in:
"C:\tools\msys64"
icon:
"%SystemDrive%\tools\msys64\clang64.exe"
- ucrt64
target: 
"C:\tools\msys64\msys2_shell.cmd -ucrt64 -defterm"
start in:
"C:\tools\msys64"
icon:
"%SystemDrive%\tools\msys64\ucrt64.exe"
- mingw64
target: 
"C:\tools\msys64\msys2_shell.cmd -mingw64 -defterm"
start in:
"C:\tools\msys64"
icon:
"%SystemDrive%\tools\msys64\mingw64.exe"

**Comment by pschneider1968** [comment]
I like the new Windows Terminal app very much for that. You can get it in the Microsoft store. It allows you to nicely configure multiple shell environments for different purposes.

grafik

**Comment by ppigazzini** [comment]
Mine :)
image

**Comment by pschneider1968** [comment]
It's good to see by this coincidence that you are already working on getting an NDK build into the Stockfish CI... Because I was thinking about trying to look into that, next weekend, too.
Now I don't have to - I'm not sure whether I should be glad or sad about that 😉😢😜

**Comment by ppigazzini** [comment]
I don't find the clang compiler :(

```
Run echo "$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
/home/runner/work/_temp/_runner_file_commands/add_path_6e66e175-f2ce-403f-a17d-8420a5e7040d
/home/runner/work/_temp/16b30528-6a8b-4db0-8b67-3784fdd03095.sh: line 4: aarch64-linux-android21-clang++: command not found
```

**Comment by ppigazzini** [comment]
Feel free to start with my wip:

https://github.com/ppigazzini/Stockfish/blob/github_ci/.github/workflows/stockfish.yml

**Comment by pschneider1968** [comment]
I'm just learning Github Actions, so it might take me a while...

But, in my test playground repo, I could find and call the NDK compiler - check this out, I hope that might help you:

https://github.com/pschneider1968/test-repo/blob/master/.github/workflows/github-actions-demo.yml

Are you running this in a Mac OS virtual env?

Also, perhaps we should close this issue, and move it to a discussion?!

**Comment by pschneider1968** [comment]
I think probably try that:
`export PATH=$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH`
instead of this:
`echo "$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH`

**Comment by ppigazzini** [comment]
It works :)
That should be the standard way to update PATH in GitHub.
Now I need to find a way to run the test with qemu-aarch64.

**Comment by pschneider1968** [comment]
I think (if you are on Debian or Ubuntu), you'd need to install:
`apt-get install qemu-user qemu-user-binfmt`

Then you should be able to just call the compiled ARM binary as if it were a native binary and have it being executed by the qemu-aarch64 emulation layer.

I don't know however, whether that is possible in the Github virtual enviroment.

**Comment by ppigazzini** [comment]
It should be needed only `apt -y install qemu-user` and the emu should be used in
https://github.com/official-stockfish/Stockfish/blob/4d3950c6eb80c932af00f6495668d5c5adf3701b/tests/signature.sh#L14

**Comment by ppigazzini** [comment]
The actions works skipping the signature check
https://github.com/ppigazzini/Stockfish/actions/runs/1803557627

**Comment by ppigazzini** [comment]
The problem is where to find the android linker/libraries to be passed to to `qemu-aarch64` to run stockfish
```
/system/bin/linker64: No such file or directory
```
Stackoverflow is down at the moment, too late to check the cached pages.

**Comment by pschneider1968** [comment]
That's a good question. I'm digging around, too...

I'm running on Debian 11.2, and have installed qemu-user and qemu-user-binfmt.

When I change the Makefile so that it is statically linked:

```
ps@deb112:~/repos/pschneider1968/Stockfish/src$ git diff
diff --git a/src/Makefile b/src/Makefile
index eff8baca..6f1cb940 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -467,7 +467,7 @@ ifeq ($(COMP),ndk)
                        STRIP=llvm-strip
                endif
        endif
-       LDFLAGS += -static-libstdc++ -pie -lm -latomic
+       LDFLAGS += -static-libstdc++ -pie -lm -latomic -static
 endif
 
 ifeq ($(comp),icc)
```

then we don't need neither the Android ELF-interpreter nor the Bionic libc shared objects. However, I then run into another issue:

```
ps@deb112:~/repos/pschneider1968/Stockfish/src$ make clean
ps@deb112:~/repos/pschneider1968/Stockfish/src$ make -j build ARCH=armv8 COMP=ndk
Default net: nn-ac07bd334b62.nnue
Already available.

Config:
debug: 'no'
sanitize: 'none'
optimize: 'yes'
.
.
aarch64-linux-android21-clang++ -Wall -Wcast-qual -fno-exceptions -std=c++17  -stdlib=libc++ -fPIE -DUSE_PTHREADS -DNDEBUG -O3 -fexperimental-new-pass-manager -DIS_64BIT -DUSE_POPCNT -DUSE_NEON=8 -flto   -c -o half_ka_v2_hm.o nnue/features/half_ka_v2_hm.cpp
aarch64-linux-android21-clang++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o tune.o tbprobe.o evaluate_nnue.o half_ka_v2_hm.o  -static-libstdc++ -pie -lm -latomic -static -Wall -Wcast-qual -fno-exceptions -std=c++17  -stdlib=libc++ -fPIE -DUSE_PTHREADS -DNDEBUG -O3 -fexperimental-new-pass-manager -DIS_64BIT -DUSE_POPCNT -DUSE_NEON=8 -flto
clang-12: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
make[1]: Verzeichnis „/home/ps/repos/pschneider1968/Stockfish/src“ wird verlassen
ps@deb112:~/repos/pschneider1968/Stockfish/src$ file stockfish 
stockfish: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, with debug_info, not stripped
ps@deb112:~/repos/pschneider1968/Stockfish/src$ make -j strip ARCH=armv8 COMP=ndk
llvm-strip stockfish
ps@deb112:~/repos/pschneider1968/Stockfish/src$ file stockfish 
stockfish: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
ps@deb112:~/repos/pschneider1968/Stockfish/src$ ./stockfish 
error: "./stockfish": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
libc: error: "./stockfish": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
qemu: uncaught target signal 6 (Aborted) - core dumped
Abgebrochen
ps@deb112:~/repos/pschneider1968/Stockfish/src$ 

```

It seems that now there is some linker flag necessary regarding segment alignment?! I guess that's too esoteric for my humble lowly knowledge, and when I try my Google-foo to find something helpfull, I stumble over a lot of pages where I even don't understand what they are talking about🤔😢

**Comment by pschneider1968** [comment]
I found that this segment alignment problem only occurs with NDK 23. If I use NDK R21e, the ARM64 stockfish executable runs with qemu:

```
ps@deb112:~/repos/pschneider1968/Stockfish/src$ echo $PATH
/home/ps/Android/NDK/bin:/home/ps/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
ps@deb112:~/repos/pschneider1968/Stockfish/src$ ls -l ~/Android
insgesamt 16
drwxr-xr-x  7 ps ps 4096  1. Jan 2010  android-studio
drwxr-xr-x  2 ps ps 4096  7. Feb 01:17 mnt
lrwxrwxrwx  1 ps ps   80  7. Feb 06:32 NDK -> /home/ps/Android/Sdk/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/
drwxr-xr-x 19 ps ps 4096  7. Feb 03:56 Sdk
ps@deb112:~/repos/pschneider1968/Stockfish/src$ aarch64-linux-android21-clang++ --version
Android (7019983 based on r365631c3) clang version 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c0edb03ba29944e529ccbf457742737b) (based on LLVM 9.0.9svn)
Target: aarch64-unknown-linux-android21
Thread model: posix
InstalledDir: /home/ps/Android/NDK/bin
ps@deb112:~/repos/pschneider1968/Stockfish/src$ make clean
ps@deb112:~/repos/pschneider1968/Stockfish/src$ make -j build ARCH=armv8 COMP=ndk
.
.
aarch64-linux-android21-clang++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o tune.o tbprobe.o evaluate_nnue.o half_ka_v2_hm.o  -static-libstdc++ -pie -lm -latomic -static -Wall -Wcast-qual -fno-exceptions -std=c++17  -stdlib=libc++ -fPIE -DUSE_PTHREADS -DNDEBUG -O3 -fexperimental-new-pass-manager -DIS_64BIT -DUSE_POPCNT -DUSE_NEON=8 -flto
clang++: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
make[1]: Verzeichnis „/home/ps/repos/pschneider1968/Stockfish/src“ wird verlassen
ps@deb112:~/repos/pschneider1968/Stockfish/src$ make -j strip ARCH=armv8 COMP=ndk
aarch64-linux-android-strip stockfish
ps@deb112:~/repos/pschneider1968/Stockfish/src$ file ./stockfish 
./stockfish: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
ps@deb112:~/repos/pschneider1968/Stockfish/src$ ./stockfish 
Stockfish 070222 by the Stockfish developers (see AUTHORS file)
compiler

Compiled by clang++ 9.0.9 on Android
Compilation settings include:  64bit POPCNT NEON
__VERSION__ macro expands to: 4.2.1 Compatible Android (7019983 based on r365631c3) Clang 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c0edb03ba29944e529ccbf457742737b)

quit
ps@deb112:~/repos/pschneider1968/Stockfish/src$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           62
Model name:                      Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
Stepping:                        4
CPU MHz:                         2699.998
BogoMIPS:                        5399.99
Virtualization:                  VT-x
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        32 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX flush not necessary, SMT disabled
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmo
                                 n rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 cx16 pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdran
                                 d hypervisor lahf_lm cpuid_fault pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms xsaveopt arat umip arch_capabilities
ps@deb112:~/repos/pschneider1968/Stockfish/src$ uname -a
Linux deb112 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
```

But it runs very slow, of course, at glacial speed... because Qemu has to translate from ARM64 ISA to my host's x86-64 ISA on the fly (and also I'm running Debian as VM, under KVM). I only get around 70k nps:

```
ps@deb112:~/repos/pschneider1968/Stockfish/src$ ./stockfish bench 2>&1 | tail -n 4
===========================
Total time (ms) : 66863
Nodes searched  : 4684080
Nodes/second    : 70054
ps@deb112:~/repos/pschneider1968/Stockfish/src$ 
```

Can that be the basis for a good profile build? I mean, the runtime characterics won't remotely resemble those of running on a real ARM64 CPU, right?

**Comment by pschneider1968** [comment]
The PGO-built binary does not run much faster:
```
ps@deb112:~/repos/pschneider1968/Stockfish/src$ ./stockfish bench 2>&1 | tail -n 4
===========================
Total time (ms) : 66028
Nodes searched  : 4684080
Nodes/second    : 70940
ps@deb112:~/repos/pschneider1968/Stockfish/src$ 
```

**Comment by ppigazzini** [comment]
PGO should be fine with qemu. The windows PGO crossbuild using Intel SDE and wine is on par with the native one.
I prefer a static build as default in the Makefile, the size should be dominated by the embedded net. But I never played with NDK, so I don't know if there are problems.
As soon as I will be at the keyboard I will try the static build for the action.
Thanks for the investigations :)

**Comment by pschneider1968** [comment]
Would it make sense (and: would it work?) to link `-static` only for the `profile-build` target, and then link dynamic for the final build with the `profile-use` target?

**Comment by ppigazzini** [comment]
It worked, great work @pschneider1968 :)

I opened the PR #3924

The Github workflow stops for any compilation warning, I fixed with:
```
LDFLAGS="-static -Wno-unused-command-line-argument" make -j2 ARCH=armv8 build 
```

Interesting reading about the GH actions:
https://yonatankra.com/7-github-actions-tricks-i-wish-i-knew-before-i-started/

> Would it make sense (and: would it work?) to link -static only for the profile-make target, and then link dynamic for the final build with the profile-use target?

We should check if a static build works fine on Android (usually is glibc that has problems).

**Comment by pschneider1968** [comment]
Sounds very good, I'm happy to hear it, and glad I could help a litte 😃👍
