### ISSUE TITLE
Compile with MinGW 10.01 "error: 'aligned_alloc"

### ISSUE THREAD

**Issue by Zerbinati** [official-stockfish/Stockfish#2838]
Maybe it had already been reported, in case I apologize.

g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -Wextra -Wshadow -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_SSSE3 -mssse3 -DUSE_SSE3 -msse3 -DUSE_SSE2   -c -o nnue/features/half_kp.o nnue/features/half_kp.cpp
nnue/evaluate_nnue.cpp: In function 'void Eval::NNUE::Detail::Initialize(Eval::NNUE::AlignedPtr<T>&)':
nnue/evaluate_nnue.cpp:60:45: error: 'aligned_alloc' is not a member of 'std'; did you mean 'aligned_union'?
   60 |     pointer.reset(reinterpret_cast<T*>(std::aligned_alloc(alignof(T), sizeof(T))));
      |                                             ^~~~~~~~~~~~~
      |                                             aligned_union
mingw32-make[2]: *** [<builtin>: nnue/evaluate_nnue.o] Error 1
mingw32-make[2]: *** Waiting for unfinished jobs....

**Comment by vondele** [comment]
yes, there is work going on trying to fix it. Compilers on some targets are not C++17 conforming.
