### ISSUE TITLE
profile count data being erased

### ISSUE THREAD

**Issue by mig2004** [official-stockfish/Stockfish#4060]
HI folks,

My compilation system has been producing error message since approximately june 2, in the testing framework, and as of today, in Github official versions,  with commit 809849f.  

I am attaching 2 snapshots (pictures) with the included error, and an image of my makefile, althought i never had trouble with the latter).  I compile with Mysys2  using tdm-gcc 10.0 with mingw-64.

 Somehow my compiler completes the builds, but it takes twice as long while going through these errors. (they are happening in every pgo build in my makefile, and errors appear in just about every sourc file compliation.) It looks ugly as hell too.

Since I dont´see anyone reporting this problem (I monitor issues on both git and fishcooking), I assume it must be on my end.  Any pointers as to what i can do on my end to fix this issue would be appreciated.

Thanks in advance.

![stockfish compilation error - makefile Captura de pantalla 2022-06-07 214439](https://user-images.githubusercontent.com/5962921/172514446-2b7af1b3-be80-4812-b0e0-cce5753d1d60.jpg)
![stockfish compilation error Captura de pantalla 2022-06-07 214224](https://user-images.githubusercontent.com/5962921/172514449-61b00083-f31f-4056-aed8-4308339b8fd1.jpg)

**Comment by move-picker** [comment]
‏

**Comment by vondele** [comment]
this does not reproduce for me on linux. I suspect it could be due to the space in 'NUEVO STOCKFISH' that something is not properly escaped somewhere. Try using a different path?

**Comment by Disservin** [comment]
This there was no update from the user afterwards I'll close it. There also have been no updates to tdm-gcc since 3 years.. https://github.com/jmeubank/tdm-gcc, I suggest migrating away from it if you haven't already.
