### ISSUE TITLE
Master does not compile on Mac OS X 10.13.6 with GCC 10.4.2

### ISSUE THREAD

**Issue by snicolet** [official-stockfish/Stockfish#7092]
### Describe the issue

Master does not compile on Mac OS X 10.13.6 with GCC 10.4.2.

Compilation stops in shm_unix.h with the following error message:

```
shm_unix.h: In member function 'Stockfish::shm::UniqueFd Stockfish::shm::SharedMemory<T>::try_receive_memfd(const std::string&)':
shm_unix.h:380:36: error: size of array 'buf' is not an integral constant-expression
  380 |                 char           buf[CMSG_SPACE(sizeof(int))];
````

### Expected behavior

Successful compilation

### Steps to reproduce

make clean
make -j build COMP=gcc

### Anything else?

The problem is that on such systems CSMG_SPACE() is not a compile time constant, so it cannot be used to allocate the size of the message buffer we use in shm_unix.h

One tentative fix using a dynamic array instead of a stack array for the message buffer has been push in pull request https://github.com/official-stockfish/Stockfish/pull/7091

### Operating system

Mac OS X (Darwin)

### Stockfish version

229f6339e537a097a79831cd06dbfdb3e623d4ac
