### PR TITLE
Fix compile bug for Mac OS X 10.13.6

### LINKED ISSUE #7092: Master does not compile on Mac OS X 10.13.6 with GCC 10.4.2
### Describe the issue

Master does not compile on Mac OS X 10.13.6 with GCC 10.4.2.

Compilation stops in shm_unix.h with the following error message:

```
shm_unix.h: In member function 'Stockfish::shm::UniqueFd Stockfish::shm::SharedMemory<T>::try_receive_memfd(const std::string&)':
shm_unix.h:380:36: error: size of array 'buf' is not an integral constant-expression
  380 |                 char           buf[CMSG_SPACE(sizeof(int))];
````

### Expected behavior

Successful compilation

### Steps to reproduce

make clean
make -j build COMP=gcc

### Anything else?

The problem is that on such systems CSMG_SPACE() is not a compile time constant, so it cannot be used to allocate the size of the message buffer we use in shm_unix.h

One tentative fix using a dynamic array instead of a stack array for the message buffer has been push in pull request https://github.com/official-stockfish/Stockfish/pull/7091

### Operating system

Mac OS X (Darwin)

### Stockfish version

229f6339e537a097a79831cd06dbfdb3e623d4ac

### PR DESCRIPTION
**Pull request by snicolet**
Master branch does not compile on some Unix systems since commit d077f9a8154df309b1b715e51d663e4cd6cf8e73 (for instance compilation fails on Mac OS X 10.13.6 using GNUC 10.4.2).

The problem is that on such systems CMSG_SPACE() is not a compile time constant, so it cannot be used to allocate the size of the message buffer we use in shm_unix.h

The fix is to use a dynamic array instead of a stack array for the buffer. We use a standard C++ vector to get automatic memory management, and align it with our utilities in memory.h.

fixes  https://github.com/official-stockfish/Stockfish/issues/7092

No functional change

### CODE REVIEW

**Comment by snicolet** [comment]
I have closed #7091 in favor of this #7093 to rebase cleanly on new master

**Comment by snicolet** [comment]
For the record, this is the AI session used to converge to the solution implemented in that patch: https://shorturl.at/u7QjD

File: src/shm_unix.h [hunk 1]
```diff
@@ -368,22 +368,19 @@ class SharedMemory {
 
         if (ret == 0)
         {
-            msghdr msg = {};
+            struct msghdr msg = {};
+            const size_t space = CMSG_SPACE(sizeof(int));
```
Comment (anematode) [inline src/shm_unix.h]: usize

Comment (snicolet) [reply src/shm_unix.h]: corrected, thanks

**Comment by anematode** [comment]
should be alignof(msghdr) rather than sizeof
