### PR TITLE
Fix a small compile error under msvc

### PR DESCRIPTION
**Pull request by mstembera**
"Error C2666 'Stockfish::operator +': 2 overloads have similar conversions \src\movepick.cpp	110"
Introduced in https://github.com/official-stockfish/Stockfish/pull/3922
No functional change.
bench: 6739741

### CODE REVIEW

**Comment by snicolet** [comment]
merged via f3a2296e591d09dd50323fc3f96e800f5538d8bb, thanks!
