### PR TITLE
Makefile ARM bugfix

### PR DESCRIPTION
**Pull request by jromang**
The gcc -m32 or -m64 option is x86 specific (see https://gcc.gnu.org/onlinedocs/gcc-6.3.0/gcc/x86-Options.html) ; using it leads to compilation error on ARM processor.

No functional change

### CODE REVIEW

**Comment by zamar** [comment]
And what do we break if we remove these flags?

I just know that we've been going back and forth between these flags, but I can't recall the details.

I can dig the archives, but hopefully someone will remember...

**Comment by jromang** [comment]
Here is the fill history in chonological order : 

The mbits option was introduced in 900279a06f432fbba63b5a320028830b40e06e3e
Then added to ARM with a3fe80c36ac8ee7677d1f6b7df9b2497e3f755c5
Then reverted e1f600f1860ccf4c3da61a7b41666f15555bb06c
Then added again 16e1881126f939383ceaaa3ec45163e760353b26

Related issues are : 
https://github.com/official-stockfish/Stockfish/issues/550
https://github.com/official-stockfish/Stockfish/issues/638
And both are related to the -m32 flag producing errors

**Comment by lucasart** [comment]
Why do you break the non ARM case ? There is a reason for this `-m$(bits)` flag. It allows to do 32-bit compile on a 64-bit machine, which is useful:
```
ifeq ($(ARCH),armv7)
	ifeq ($(OS),Android)
		CXXFLAGS += -m$(bits)
		LDFLAGS += -m$(bits)
	endif
else
	// Why do you break that ?
	CXXFLAGS += -m$(bits)
	LDFLAGS += -m$(bits)
endif
```

**Comment by jromang** [comment]
@lucasart
The -m$(bits) flag does not allow 32 bit compiles on ARM : it's not a valid gcc option for ARM processors.
See compilation problems on raspberry pi : 
http://support.stockfishchess.org/discussions/problems/7805-compiling-stockfish-8-on-raspberry-pi-3

**Comment by zamar** [comment]
@jromang: sure, but why do you want to remove these flags also for *non* ARM compiles.

**Comment by zamar** [comment]
@jromang: So currently the flags are included for non-ARM compiles and for ARM-compiles if OS is not android.

Isn't this more or less what you're asking for? Or are you compiling for Android and having trouble with these flags?

**Comment by jromang** [comment]
In fact, those flags are x86 specific (see gcc man page) : everyone trying to build stockfish on anything else than x86 should see an error ; I tried only on ARM platform, but anyone trying on a PPC or other kind of processor should see an error. That's why I think we should remove it.
I don't see anything related to android there, and I don't understand why there is a specific android test : it's only a gcc processor specific option, nothing related to an OS.

Maybe the conservative way would be to keep something like  : 
`ifeq ($(ARCH),i386)
		CXXFLAGS += -m$(bits)
		LDFLAGS += -m$(bits)
	endif

ifeq ($(ARCH),x86_64)
		CXXFLAGS += -m$(bits)
		LDFLAGS += -m$(bits)
	endif
`

**Comment by vondele** [comment]
hm, not quite. I can build current master on power8 (ppc64le), make ARCH=ppc-64 build works fine (includes -m64), and the binary gives the correct bench.

**Comment by vondele** [comment]
so it turns out -m64 is not only x86, but quite a few other architectures including powerPC
https://gcc.gnu.org/onlinedocs/gcc/Option-Summary.html
ARM, doesn't seem to have it, however, but I can't test right now.

**Comment by jromang** [comment]
@vondele, you are right, I missed that.
So what is the right thing to do ? Maybe only keep the -m32 option for i386 arch and  ppc-32 ?

**Comment by vondele** [comment]
@jromang I agree that the current setup is wrong, i.e. '-m${bits}' can not just be added to the compiler flags, since it depends on the architecture, and on arm this should fail. 

However, I don't know why there is the distinction between Android and not on ARM, so I can't tell what the right solution is.

**Comment by zamar** [comment]
For me it looks like that the correct way is to add a new architecture specific option which dictates whether we pass -m flag or not.

**Comment by jromang** [comment]
@zamar ; ok I'll do that !

**Comment by vondele** [comment]
@jromang, actually, I could compile on ARM with a linux OS. It looks like the problem can only happen with Android. An eventual fix needs to understand why Android is added as an exception.

what is also inconsistent is that the ARCH=armv7 is actually not an architecture but a CPU. The architecture would be ARM and could be both 32 or 64 bits.

That also brings me to the question what is IS_64BIT really defining, i.e. what does that signal inside the code. Is this about the size of a pointer, or the word size (ILP64 or what?)

**Comment by jromang** [comment]
@vondele : what linux/gcc version are you using ? I tried to build on linux (not android) and it failed.
armv7 is 32 bit, armv8 is 64 bit : so I may add three archs :

- armv7
- armv7-android (with the mysterious '-m' flag)
- armv8

Also, I think they are achitectures, not CPUs, for exemple there are many armv7 processors (https://en.wikipedia.org/wiki/Comparison_of_ARMv7-A_cores)

**Comment by jromang** [comment]
@vondele it seems IS_64BIT was used to optimize the speed some bitboard functions in the past (https://github.com/official-stockfish/Stockfish/blob/9bbd27a80f707230dfdf1f553716b1e1bfaf330a/src/bitboard.cpp) ; I can't see a usage in the actual code yet.

**Comment by vondele** [comment]
@jromang confusing ARM ecosystem ;-) 

I actually ran on aarch64 Ubuntu 14.04 LTS (GNU/Linux 3.18.0+ aarch64), which I think is ARMv8

**Comment by vondele** [comment]
IS_64BIT turns into Is64Bit, which sets both the hash size and accelerates DeBruijn sequences. 

However, I would guess that one thing needs 64 bit pointers and the other efficient 64 bit integers ? That doesn't need to be the same, for example x32 ABI (but I guess the pointers is enough to guarantee the integers).

**Comment by jromang** [comment]
@vondele ; so you are using gcc 4.8 ?
I can't find the -m32 / -m64 options in the gcc options list for this version (https://gcc.gnu.org/onlinedocs/gcc-4.8.2/gcc/ARM-Options.html#ARM-Options)...maybe this version of gcc is just more tolerent by ignoring the flag ?

**Comment by vondele** [comment]
yes gcc version 4.8.2 (Ubuntu/Linaro 4.8.2-19ubuntu1) Target: aarch64-linux-gnu

but note that the flag is not added by the makefile (make -j ARCH=armv7 build) in this case:
```
ifeq ($(COMP),gcc)
[...]
        ifeq ($(ARCH),armv7)
                ifeq ($(OS),Android)
                        CXXFLAGS += -m$(bits)
                        LDFLAGS += -m$(bits)
                endif
        else
                CXXFLAGS += -m$(bits)
                LDFLAGS += -m$(bits)
        endif

```
it only happens with ARCH=armv7 and OS=Android. Consistent with this it doesn't appear in the compile options, and gcc has nothing to ignore.

Are we seeing something different ?

**Comment by zamar** [comment]
This patch is not committable.

As @vondele pointed out the "-mbits" is not used in armv target by default.

So closing this one.
